### ISSUE TITLE
I like your theme, could you help me for some css optimization？

### ISSUE THREAD

**Issue by jlhxxxx** [jsliang/pelican-fresh#15]
Could you add some css to <table> and <blockquote> to make them easier to distinguish, here is the example page: <https://jlhxxxx.github.io/jmeter-doc-cn-20.html>, thank you!

**Comment by jlhxxxx** [comment]
That's \<table\> and \<blockquote\>

**Comment by jlhxxxx** [comment]
I have made some change myself and pulled to you, you can check it. Thank you anyway！

**Comment by jsliang** [comment]
Hi @jlhxxxx, thank you for the PR. And sorry for the late reply. 🙇‍♀
